/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

group = "com.dre"
version = "3.1.1"
description = "Brewery"
java.sourceCompatibility = JavaVersion.VERSION_17

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.md-5.net/content/groups/public/")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://nexus.hc.to/content/repositories/pub_releases")
    }

    maven {
        url = uri("https://maven.enginehub.org/repo/")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://ci.ender.zone/plugin/repository/everything/")
    }

    maven {
        url = uri("https://repo.minebench.de/")
    }

    maven {
        url = uri("https://repo.codemc.org/repository/maven-public/")
    }

    maven {
        url = uri("https://nexus.phoenixdevt.fr/repository/maven-public/")
    }

    maven {
        url = uri("https://nexus.lichtspiele.org/repository/releases/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.bstats:bstats-bukkit:3.0.2")
    api("org.jetbrains:annotations:20.1.0")

    compileOnly("org.spigotmc:spigot-api:1.20.2-R0.1-SNAPSHOT")
    compileOnly("net.milkbowl.vault:VaultAPI:1.6")
    compileOnly("com.sk89q:worldguard:6.1")
    compileOnly("com.sk89q.worldedit:worldedit-bukkit:7.3.0-SNAPSHOT")
    compileOnly("com.sk89q.worldedit:worldedit-core:7.3.0-SNAPSHOT")
    compileOnly("com.sk89q.worldguard:worldguard-core:7.0.9")
    compileOnly("com.griefcraft.lwc:LWCX:2.2.9-dev")
    compileOnly("com.github.TechFortress:GriefPrevention:16.18.1")
    compileOnly("de.diddiz:logblock:1.16.5.1")
    compileOnly("com.github.Slimefun:Slimefun4:RC-36")
    compileOnly("io.lumine:MythicLib-dist:1.6-SNAPSHOT")
    compileOnly("com.acrobot.chestshop:chestshop:3.12.2")
    compileOnly("com.github.TownyAdvanced.Towny:towny:0.100.1.16")
    compileOnly("com.nisovin.shopkeepers:ShopkeepersAPI:2.19.0")
    compileOnly("nl.rutgerkok:blocklocker:1.10.4")
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}
